# Generated by Django 4.2.16 on 2025-01-01 00:43

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='', max_length=100, validators=[api.models.validate_email_format]),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Transferencias', 'Transferencias'), ('Abonos', 'Abonos'), ('Pagos de Efectivo', 'Pagos Efectivo'), ('Devoluciones', 'Devoluciones'), ('Sobrantes', 'Sobrantes'), ('Préstamos con Interés', 'Prestamos Con Interes'), ('Préstamos sin Interés', 'Prestamos Sin Interes'), ('Regalos', 'Regalos'), ('Encontrados', 'Encontrados'), ('Sin Justificar', 'Sin Justificar')], default='Sin Justificar', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.usuario')),
            ],
        ),
    ]
